apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: mypod
spec:
  containers:
  - name: mycontainer
    image: demo:v2
    args:
      ["echo", "a pod"]
    resources:
      limits:
        memory: "32Mi"
        cpu: "200m"
