apiVersion: v1
kind: Pod
metadata:
  name: hello-spring
spec:
  containers:
  - name: hello-spring
    image: hello-spring:v0.3
    readinessProbe:
      httpGet:
        path: /actuator/health/readiness
        port: 8080
      initialDelaySeconds: 30
      timeoutSeconds: 2
      periodSeconds: 3
      failureThreshold: 1
    livenessProbe:
      httpGet:
        path: /actuator/health/liveness
        port: 8080
      initialDelaySeconds: 20
      timeoutSeconds: 2
      periodSeconds: 8
      failureThreshold: 1
