apiVersion: v1
kind: Pod
metadata:
  name: demo-restartpolicy
spec:
  containers:
  - name: centos
    image: centos:7
    command: ["bash","-c",
      "sleep 40;
       ls /root/a"]
  restartPolicy: OnFailure
