apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-prestop-hook
spec:
  selector:
    matchLabels:
      app: demo-prestop-hook
  template:
    metadata:
      labels:
        app: demo-prestop-hook
    spec:
      containers:
      - name: demo-prestop-hook
        image: nginx:1.18-alpine-perl
        lifecycle:
          preStop:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - " \
                  APPLICATION=NAME-service; \
                  APPLICATION_PORT=8016; \
                  curl -s -X PUT http://eureka-1.microservices-system/eureka/apps/${APPLICATION}/$(hostname):${APPLICATION}:${APPLICATION_PORT}/status?value=OUT_OF_SERVICE; \
                  sleep 30; \
                  "
