apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-prestop-hook
  labels:
    app: demo
    kind: web
spec:
  containers:
  - name: nginx
    image: nginx:1.19-alpine-perl
    lifecycle:
      preStop:
        exec:
          command:
          - sleep
          - "30"
