apiVersion: v1
kind: Service
metadata:
  name: stateful-deploy
spec:
  ports:
  - port: 80
  selector:
    app: stateful-deploy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateful-deploy
spec:
  selector:
    matchLabels:
      app: stateful-deploy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: stateful-deploy
    spec:
      containers:
      - image: nginx:1.19-alpine-perl 
        name: nginx
        volumeMounts:
        - name: stfdeploy-storage
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: stfdeploy-storage
        persistentVolumeClaim:
          claimName: pvc01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc01
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi

