apiVersion: v1
kind: Service
metadata:
  name: statefulweb
  labels:
    app: statefulweb
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: statefulweb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "statefulweb"
  replicas: 2
  selector:
    matchLabels:
      app: statefulweb
  template:
    metadata:
      labels:
        app: statefulweb
    spec:
      containers:
      - name: nginx
        image: nginx:1.19-alpine-perl
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: init-index
        image: busybox:1.28.4
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
        command: ["sh", "-c",
                  "[[ -f /usr/share/nginx/html/index.html ]] && exit 0;
                   echo $(date -R) > /usr/share/nginx/html/index.html"]
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Mi


